services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: kratos-dev

    volumes:
      - ./backend/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  api:
    image: krystofjan/kratos-gym-be:latest
    depends_on:
      - postgres
    network_mode: "host"
    ports:
      - 7000:7000

  frontend:
    image: krystofjan/kratos-gym-fe:latest
    depends_on:
      - api
    network_mode: "host"
    ports:
      - 5173:5173

