URL = "localhost"
PORT = 8080

WrkOutMachineNames = [
    'Treadmill',
    'Elliptical Trainer',
    'Stationary Bike',
    'Rowing Machine',
    'Stair Climber',
    'Smith Machine',
    'Leg Press',
    'Chest Press Machine',
    'Lat Pulldown Machine',
    'Seated Row Machine',
    'Cable Crossover Machine',
    'Leg Curl Machine',
    'Leg Extension Machine',
    'Pec Deck Machine',
    'Shoulder Press Machine',
    'Hack Squat Machine',
    'Ab Crunch Machine',
    'Tricep Dip Machine',
    'Bicep Curl Machine',
    'Back Extension Machine',
    'Hip Abductor Machine',
    'Hip Adductor Machine',
    'Glute Bridge Machine',
    'Calf Raise Machine',
    'Vertical Knee Raise Machine',
    'Assisted Pull-Up Machine',
    'Multi-Gym Machine',
    'Power Rack',
    'Squat Rack',
    'Preacher Curl Bench',
    'Hyperextension Bench',
    'Smith Machine Squat',
    'Incline Chest Press Machine',
    'Decline Chest Press Machine',
    'Lateral Raise Machine',
    'Fly Machine',
    'Rear Delt Machine',
    'Inner Thigh Machine',
    'Outer Thigh Machine',
    'Seated Calf Raise Machine',
    'Glute Ham Developer',
    'Seated Leg Press Machine',
    'Standing Calf Raise Machine',
    'Ab Coaster Machine',
    'Total Gym',
    'CrossFit Rig',
    'Battle Ropes',
    'Sled Push Machine',
    'Plyo Box',
    'Air Bike',
    'Power Tower',
    'Vertical Leg Press Machine',
    'Cable Pulley Machine',
    'Smith Machine Bench Press',
    'Leg Adduction Machine',
    'Leg Abduction Machine',
    'Inner / Outer Thigh Machine',
    'Pec Fly Machine',
    'Dual Pulley Machine',
    'Assisted Tricep Dip Machine',
    'Decline Ab Bench',
    'Ab Roller Machine',
    'Hyperextension Chair',
    'StepMill Machine',
    'Stretch Trainer Machine',
    'Abdominal Twist Machine',
    'Rotary Torso Machine',
    'Glute Kickback Machine',
    'Seated Chest Press Machine',
    'Overhead Press Machine',
    'Hip Thrust Machine',
    'Rotary Lat Machine',
    'Lat Raise Machine',
    'Bench Press Machine',
    'Smith Machine Incline Bench',
    'FreeMotion Machine',
    'Gravity Machine',
    'Rope Climb Machine',
    'Cable Row Machine',
    'Seated Calf Machine',
    'Standing Leg Curl Machine',
    'Seated Leg Curl Machine',
    'Chest Fly Machine',
    'Rotary Calf Machine',
    'Lateral Squat Machine',
    'Torso Rotation Machine',
    'Vertical Chest Press Machine',
    'Horizontal Leg Press Machine',
    'Plate-Loaded Leg Press Machine',
    'Hammer Strength Machine',
    'Smith Machine Deadlift',
    'Cable Crossover Station',
    'Bicep Curl Station',
    'Tricep Extension Machine',
    'Wrist Curl Machine',
    'T-Bar Row Machine',
    'Landmine Attachment',
    'Suspension Trainer',
    'Vibration Plate Machine',
    'Airdyne Bike'
]
Categories = [
    'Cardiovascular',
    'Strength Training',
    'High-Intensity Interval Training (HIIT)',
    'Flexibility Training',
    'Core Workouts',
    'Endurance Training',
    'Bodybuilding',
    'Powerlifting',
    'CrossFit',
    'Functional Training',
    'Balance Training',
    'Circuit Training',
    'Plyometrics',
    'Aerobic Workouts',
    'Anaerobic Workouts',
    'Yoga',
    'Pilates',
    'Stretching',
    'Rehabilitation Workouts',
    'Sport-Specific Training',
    'Agility Training',
    'Resistance Band Training',
    'Kettlebell Training',
    'Bodyweight Training',
    'Dance Workouts'
]

BodyParts = [
    'Shoulders',
    'Triceps',
    'Biceps',
    'Forearms',
    'Chest',
    'Upper Back',
    'Lower Back',
    'Lats',
    'Trapezius',
    'Abs',
    'Obliques',
    'Glutes',
    'Quadriceps',
    'Hamstrings',
    'Calves',
    'Hip Flexors',
    'Adductors',
    'Abductors',
    'Erector Spinae',
    'Neck',
    'Deltoids',
    'Rotator Cuff',
    'Serratus Anterior',
    'Rhomboids',
    'Transverse Abdominis',
    'Soleus',
    'Gastrocnemius',
    'Tibialis Anterior',
    'Sartorius',
    'Pectorals',
    'Rectus Abdominis',
    'Iliopsoas',
    'Teres Major',
    'Teres Minor',
    'Infraspinatus',
    'Supraspinatus',
    'Brachialis',
    'Brachioradialis',
    'Flexor Carpi Radialis',
    'Extensor Carpi Ulnaris'
]
