name: Test Docker Container
on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Get Docker Tag
        id: get_tag
        run: echo "docker_tag=${{ github.event.workflow_run.outputs.docker_tag }}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker Image
        run: |
          echo "Pulling Docker image with tag: ${{ env.docker_tag }}"
          docker pull krystofjan/kratos-gym-be:${{ env.docker_tag }}

      - name: Run Tests in Docker Container
        run: |
          docker run --rm -v ${{ github.workspace }}/backend/tests:/app/tests krystofjan/kratos-gym-be:${{ env.docker_tag }} sh -c "pip install requirements.txt && pytest /app/tests"

