name: Delete Docker Tag
on:
  pull_request:
    types: [closed]  

jobs:
  delete-tag:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged }} 
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Delete Docker Image Tag
        run: |
          # Determine the tag to delete
          PR_NUMBER=${{ github.event.pull_request.number }}
          TAG="pr-${PR_NUMBER}"
          echo "Deleting Docker image tag: krystofjan/kratos-gym-be:${TAG}"
          docker rmi krystofjan/kratos-gym-be:${TAG} || true  # Remove local image
          curl -X DELETE "https://hub.docker.com/v2/repositories/krystofjan/kratos-gym-be/tags/${TAG}/"  # Delete the tag from Docker Hub

