name: Docker CI
on:
  push:
    branches: [master, main]
    paths:
      - 'backend/**' 
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'backend/**'  

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.docker_tag.outputs.tag }}
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set Up Docker build
        uses: docker/setup-buildx-action@v2
      
      - name: Determine Docker Tag
        id: docker_tag
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "tag=latest" >> $GITHUB_ENV
            echo "tag=latest" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "tag=pr-${{ github.event.number }}" >> $GITHUB_ENV
            echo "tag=pr-${{ github.event.number }}" >> $GITHUB_OUTPUT
          fi
      
      - name: Build docker image
        run: |
          docker build -t krystofjan/kratos-gym-be:${{ env.tag }} ./backend
      
      - name: Push Docker image
        run: |
          docker push krystofjan/kratos-gym-be:${{ env.tag }}

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Pull Docker Image
        run: |
          echo "Pulling Docker image with tag: ${{ needs.build.outputs.docker_tag }}"
          docker pull krystofjan/kratos-gym-be:${{ needs.build.outputs.docker_tag }}
      
      - name: Run Tests in Docker Container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/backend/tests:/app/tests \
            krystofjan/kratos-gym-be:${{ needs.build.outputs.docker_tag }} \
            sh -c "cd /app/tests && apt-get update && apt-get install -y python3-pip && python3 -m pip install -r requirements.txt && python3 -m pytest"
