name: Test Docker Container
on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Determine Docker Tag
        id: docker_tag
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "tag=latest" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "tag=pr-${{ github.event.number }}" >> $GITHUB_ENV
          fi

      - name: Pull Docker Image
        run: |
          docker pull krystofjan/kratos-gym-be:${{ env.tag }}

      - name: Run Tests in Docker Container
        run: |
          docker run --rm -v ${{ github.workspace }}/backend/tests:/app/tests krystofjan/kratos-gym-be:${{ env.tag }} sh -c "pip install requirements.txt && pytest /app/tests"

