name: Build docker image
on:
  push:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Up Docker build
        uses: docker/setup-buildx-action@v2


      - name: build docker image
        run: |
          docker build -t krystofjan/kratos-gym-be:tagname ./backend

      - name: Push Docker imag
        run: |
          docker push my-backend-image:latest

