name: Build Docker Image
on:
  push:
    branches: [master, main]
    paths:
      - 'backend/**' 
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'backend/**'  

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.docker_tag.outputs.tag }}  
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Up Docker build
        uses: docker/setup-buildx-action@v2

      - name: Determine Docker Tag
        id: docker_tag
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "tag=latest" >> $GITHUB_ENV
            echo "::set-output name=tag::latest"
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "tag=pr-${{ github.event.number }}" >> $GITHUB_ENV
            echo "::set-output name=tag::pr-${{ github.event.number }}"
          fi

      - name: build docker image
        run: |
          docker build -t krystofjan/kratos-gym-be:${{ env.tag }} ./backend

      - name: Push Docker imag
        run: |
          docker push krystofjan/kratos-gym-be:${{ env.tag }}

